#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AiTask

#include "Basic.hpp"

#include "AiTask_classes.hpp"
#include "AiTask_parameters.hpp"


namespace SDK
{

// Function AiTask.AiTask_C.TaskComplete__DelegateSignature
// (Public, Delegate, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FST_Task                         Param_Task                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAiTask_C::TaskComplete__DelegateSignature(const struct FST_Task& Param_Task)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AiTask_C", "TaskComplete__DelegateSignature");

	Params::AiTask_C_TaskComplete__DelegateSignature Parms{};

	Parms.Param_Task = std::move(Param_Task);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AiTask.AiTask_C.Reset
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FST_Task                         Param_Task                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAiTask_C::Reset(const struct FST_Task& Param_Task)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AiTask_C", "Reset");

	Params::AiTask_C_Reset Parms{};

	Parms.Param_Task = std::move(Param_Task);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AiTask.AiTask_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAiTask_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AiTask_C", "ReceiveTick");

	Params::AiTask_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AiTask.AiTask_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AAiTask_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AiTask_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AiTask.AiTask_C.ExecuteUbergraph_AiTask
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAiTask_C::ExecuteUbergraph_AiTask(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AiTask_C", "ExecuteUbergraph_AiTask");

	Params::AiTask_C_ExecuteUbergraph_AiTask Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AiTask.AiTask_C.Complete
// (BlueprintCallable, BlueprintEvent)

void AAiTask_C::Complete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AiTask_C", "Complete");

	UObject::ProcessEvent(Func, nullptr);
}

}

