#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AiController

#include "Basic.hpp"

#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AiController.BP_AiController_C
// 0x0000 (0x03B8 - 0x03B8)
class ABP_AiController_C final : public AAIController
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AiController_C">();
	}
	static class ABP_AiController_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_AiController_C>();
	}
};
static_assert(alignof(ABP_AiController_C) == 0x000008, "Wrong alignment on ABP_AiController_C");
static_assert(sizeof(ABP_AiController_C) == 0x0003B8, "Wrong size on ABP_AiController_C");

}

