#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CoreWidget

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BP_CoreWidget.BP_CoreWidget_C
// 0x0000 (0x0278 - 0x0278)
class UBP_CoreWidget_C : public UUserWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CoreWidget_C">();
	}
	static class UBP_CoreWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CoreWidget_C>();
	}
};
static_assert(alignof(UBP_CoreWidget_C) == 0x000008, "Wrong alignment on UBP_CoreWidget_C");
static_assert(sizeof(UBP_CoreWidget_C) == 0x000278, "Wrong size on UBP_CoreWidget_C");

}

