#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CinematicPawn

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "EnhancedInput_structs.hpp"
#include "Engine_structs.hpp"
#include "PhysicsCore_structs.hpp"


namespace SDK::Params
{

// Function BP_CinematicPawn.BP_CinematicPawn_C.Zoom
// 0x0001 (0x0001 - 0x0000)
struct BP_CinematicPawn_C_Zoom final
{
public:
	bool                                          Param_Zoom;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CinematicPawn_C_Zoom) == 0x000001, "Wrong alignment on BP_CinematicPawn_C_Zoom");
static_assert(sizeof(BP_CinematicPawn_C_Zoom) == 0x000001, "Wrong size on BP_CinematicPawn_C_Zoom");
static_assert(offsetof(BP_CinematicPawn_C_Zoom, Param_Zoom) == 0x000000, "Member 'BP_CinematicPawn_C_Zoom::Param_Zoom' has a wrong offset!");

// Function BP_CinematicPawn.BP_CinematicPawn_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct BP_CinematicPawn_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CinematicPawn_C_ReceiveTick) == 0x000004, "Wrong alignment on BP_CinematicPawn_C_ReceiveTick");
static_assert(sizeof(BP_CinematicPawn_C_ReceiveTick) == 0x000004, "Wrong size on BP_CinematicPawn_C_ReceiveTick");
static_assert(offsetof(BP_CinematicPawn_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'BP_CinematicPawn_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function BP_CinematicPawn.BP_CinematicPawn_C.OnClick_Event
// 0x0008 (0x0008 - 0x0000)
struct BP_CinematicPawn_C_OnClick_Event final
{
public:
	class UClickableText_C*                       Text;                                              // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CinematicPawn_C_OnClick_Event) == 0x000008, "Wrong alignment on BP_CinematicPawn_C_OnClick_Event");
static_assert(sizeof(BP_CinematicPawn_C_OnClick_Event) == 0x000008, "Wrong size on BP_CinematicPawn_C_OnClick_Event");
static_assert(offsetof(BP_CinematicPawn_C_OnClick_Event, Text) == 0x000000, "Member 'BP_CinematicPawn_C_OnClick_Event::Text' has a wrong offset!");

// Function BP_CinematicPawn.BP_CinematicPawn_C.OnActorBeginOverlap_Event
// 0x0010 (0x0010 - 0x0000)
struct BP_CinematicPawn_C_OnActorBeginOverlap_Event final
{
public:
	class AActor*                                 OverlappedActor;                                   // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OtherActor;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CinematicPawn_C_OnActorBeginOverlap_Event) == 0x000008, "Wrong alignment on BP_CinematicPawn_C_OnActorBeginOverlap_Event");
static_assert(sizeof(BP_CinematicPawn_C_OnActorBeginOverlap_Event) == 0x000010, "Wrong size on BP_CinematicPawn_C_OnActorBeginOverlap_Event");
static_assert(offsetof(BP_CinematicPawn_C_OnActorBeginOverlap_Event, OverlappedActor) == 0x000000, "Member 'BP_CinematicPawn_C_OnActorBeginOverlap_Event::OverlappedActor' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_OnActorBeginOverlap_Event, OtherActor) == 0x000008, "Member 'BP_CinematicPawn_C_OnActorBeginOverlap_Event::OtherActor' has a wrong offset!");

// Function BP_CinematicPawn.BP_CinematicPawn_C.InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0
// 0x0030 (0x0030 - 0x0000)
struct BP_CinematicPawn_C_InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0 final
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CinematicPawn_C_InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0) == 0x000008, "Wrong alignment on BP_CinematicPawn_C_InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0");
static_assert(sizeof(BP_CinematicPawn_C_InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0) == 0x000030, "Wrong size on BP_CinematicPawn_C_InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0");
static_assert(offsetof(BP_CinematicPawn_C_InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0, ActionValue) == 0x000000, "Member 'BP_CinematicPawn_C_InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0::ActionValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0, ElapsedTime) == 0x000020, "Member 'BP_CinematicPawn_C_InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0::ElapsedTime' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0, TriggeredTime) == 0x000024, "Member 'BP_CinematicPawn_C_InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0::TriggeredTime' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0, SourceAction) == 0x000028, "Member 'BP_CinematicPawn_C_InpActEvt_IA_Use_K2Node_EnhancedInputActionEvent_0::SourceAction' has a wrong offset!");

// Function BP_CinematicPawn.BP_CinematicPawn_C.InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1
// 0x0030 (0x0030 - 0x0000)
struct BP_CinematicPawn_C_InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1 final
{
public:
	struct FInputActionValue                      ActionValue;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	float                                         ElapsedTime;                                       // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TriggeredTime;                                     // 0x0024(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     SourceAction;                                      // 0x0028(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CinematicPawn_C_InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1) == 0x000008, "Wrong alignment on BP_CinematicPawn_C_InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1");
static_assert(sizeof(BP_CinematicPawn_C_InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1) == 0x000030, "Wrong size on BP_CinematicPawn_C_InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1");
static_assert(offsetof(BP_CinematicPawn_C_InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1, ActionValue) == 0x000000, "Member 'BP_CinematicPawn_C_InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1::ActionValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1, ElapsedTime) == 0x000020, "Member 'BP_CinematicPawn_C_InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1::ElapsedTime' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1, TriggeredTime) == 0x000024, "Member 'BP_CinematicPawn_C_InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1::TriggeredTime' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1, SourceAction) == 0x000028, "Member 'BP_CinematicPawn_C_InpActEvt_IA_Move_K2Node_EnhancedInputActionEvent_1::SourceAction' has a wrong offset!");

// Function BP_CinematicPawn.BP_CinematicPawn_C.ExecuteUbergraph_BP_CinematicPawn
// 0x0A30 (0x0A30 - 0x0000)
struct BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_298E[0x4];                                     // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              Temp_struct_Variable;                              // 0x0008(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMovementMode                                 Temp_byte_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_298F[0x7];                                     // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_BreakVector2D_X;                          // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_Y;                          // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EMovementMode                                 Temp_byte_Variable_1;                              // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2990[0x7];                                     // 0x0031(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x0038(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SelectFloat_ReturnValue_1;                // 0x0050(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UClickableText_C*                       CallFunc_Create_ReturnValue;                       // 0x0058(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x0060(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	TDelegate<void(class UClickableText_C* Text)> K2Node_CreateDelegate_OutputDelegate;              // 0x0070(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_DialogBox_C*                       CallFunc_Create_ReturnValue_1;                     // 0x0080(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0088(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0098(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UWBP_rec_effect_C*                      CallFunc_Create_ReturnValue_2;                     // 0x00A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Lerp_ReturnValue;                         // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue;       // 0x00B8(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime;       // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime;     // 0x00DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     K2Node_EnhancedInputActionEvent_SourceAction;      // 0x00E0(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           Temp_object_Variable;                              // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Conv_InputActionValueToBool_ReturnValue;  // 0x00F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2991[0x7];                                     // 0x00F1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Temp_real_Variable;                                // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_1;                              // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_0;                              // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_1_0;                            // 0x0110(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2992[0x7];                                     // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             Temp_struct_Variable_1;                            // 0x0120(0x0060)(ConstParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             Temp_struct_Variable_2;                            // 0x0180(0x0060)(ConstParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_AddComponent_ReturnValue;                 // 0x01E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_AddComponent_ReturnValue_1;               // 0x01E8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class AActor* OverlappedActor, class AActor* OtherActor)> K2Node_CreateDelegate_OutputDelegate_3;            // 0x01F0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTransform                             Temp_struct_Variable_3;                            // 0x0200(0x0060)(ConstParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x0260(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0270(0x0008)(NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_AddComponent_ReturnValue_2;               // 0x0278(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UNewWidgetBlueprint_C*                  CallFunc_Create_ReturnValue_3;                     // 0x0280(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EPhysicalSurface                              Temp_byte_Variable_2;                              // 0x0288(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2993[0x7];                                     // 0x0289(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             Temp_object_Variable_1;                            // 0x0290(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Temp_object_Variable_2;                            // 0x0298(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Temp_object_Variable_3;                            // 0x02A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Temp_object_Variable_4;                            // 0x02A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             Temp_object_Variable_5;                            // 0x02B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         Temp_object_Variable_6;                            // 0x02B8(0x0010)(ConstParm, ReferenceParm)
	bool                                          Temp_bool_Variable_1;                              // 0x02C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2994[0x7];                                     // 0x02C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x02D0(0x0018)(ConstParm)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x02E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable;                 // 0x02E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable;                       // 0x02EA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2995[0x1];                                     // 0x02EB(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x02EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x02F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x02F4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_2;                              // 0x02F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_GetControlRotation_ReturnValue;           // 0x0300(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_GetControlRotation_ReturnValue_1;         // 0x0318(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x0330(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x0334(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x0338(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Roll_1;                      // 0x033C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch_1;                     // 0x0340(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw_1;                       // 0x0344(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0348(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_1;                // 0x0360(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_GetForwardVector_ReturnValue;             // 0x0378(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetRightVector_ReturnValue;               // 0x0390(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable_1;                              // 0x03A8(0x0018)(ConstParm)
	double                                        Temp_real_Variable_3;                              // 0x03C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UInputAction*                           Temp_object_Variable_7;                            // 0x03C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_GetControlRotation_ReturnValue_2;         // 0x03D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_GetRightVector_ReturnValue_1;             // 0x03E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_RotatorToVector_ReturnValue;         // 0x0400(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0418(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2996[0x4];                                     // 0x041C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                K2Node_Select_Default;                             // 0x0420(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                K2Node_Select_Default_1;                           // 0x0438(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0450(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AHUD*                                   CallFunc_GetHUD_ReturnValue;                       // 0x0458(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UStackBoxSlot*                          CallFunc_AddChildToStackBox_ReturnValue;           // 0x0460(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class ABP_GrannyHUD_C*                        K2Node_DynamicCast_AsBP_Granny_HUD;                // 0x0468(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0470(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2997[0x7];                                     // 0x0471(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UClickableText_C*                       K2Node_CustomEvent_Text;                           // 0x0478(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UStackBoxSlot*                          CallFunc_AddChildToStackBox_ReturnValue_1;         // 0x0480(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable_2;                              // 0x0488(0x0018)(ConstParm)
	struct FInputActionValue                      K2Node_EnhancedInputActionEvent_ActionValue_1;     // 0x04A0(0x0020)(NoDestructor)
	float                                         K2Node_EnhancedInputActionEvent_ElapsedTime_1;     // 0x04C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_EnhancedInputActionEvent_TriggeredTime_1;   // 0x04C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UInputAction*                     K2Node_EnhancedInputActionEvent_SourceAction_1;    // 0x04C8(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_3_0;                            // 0x04D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Temp_real_Variable_2_0;                            // 0x04D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_Conv_InputActionValueToAxis2D_ReturnValue; // 0x04E0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable_3;                              // 0x04F0(0x0018)(ConstParm)
	bool                                          K2Node_CustomEvent_Zoom;                           // 0x0508(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2998[0x7];                                     // 0x0509(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x0510(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   Temp_text_Variable_4;                              // 0x0518(0x0018)(ConstParm)
	TArray<class ATriggerBox*>                    CallFunc_GetAllActorsOfClassWithTag_OutActors;     // 0x0530(0x0010)(ReferenceParm)
	class ATriggerBox*                            CallFunc_Array_Get_Item;                           // 0x0540(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_CustomEvent_OverlappedActor;                // 0x0548(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_CustomEvent_OtherActor;                     // 0x0550(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TArray<class ATargetPoint*>                   CallFunc_GetAllActorsOfClassWithTag_OutActors_1;   // 0x0558(0x0010)(ReferenceParm)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0568(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2999[0x7];                                     // 0x0569(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ATargetPoint*                           CallFunc_Array_Get_Item_1;                         // 0x0570(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0578(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0590(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0598(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_FindLookAtRotation_ReturnValue;           // 0x05B0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class AController*                            CallFunc_GetController_ReturnValue_1;              // 0x05C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_1;        // 0x05D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_GrannyController_C*                 K2Node_DynamicCast_AsBP_Granny_Controller;         // 0x05D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x05E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_299A[0x7];                                     // 0x05E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AHUD*                                   CallFunc_GetHUD_ReturnValue_1;                     // 0x05E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_GrannyHUD_C*                        K2Node_DynamicCast_AsBP_Granny_HUD_1;              // 0x05F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x05F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_299B[0x7];                                     // 0x05F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerCameraManager*                   CallFunc_GetPlayerCameraManager_ReturnValue;       // 0x0600(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULegacyCameraShake*                     CallFunc_StartLegacyCameraShake_ReturnValue;       // 0x0608(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue_2;        // 0x0610(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AHUD*                                   CallFunc_GetHUD_ReturnValue_2;                     // 0x0618(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Has_Been_Initd_Variable_1;               // 0x0620(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_299C[0x7];                                     // 0x0621(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_GrannyHUD_C*                        K2Node_DynamicCast_AsBP_Granny_HUD_2;              // 0x0628(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0630(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_299D[0x7];                                     // 0x0631(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x0638(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_2;    // 0x0650(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_3;    // 0x0668(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_FindLookAtRotation_ReturnValue_1;         // 0x0680(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         CallFunc_BreakRotator_Roll_2;                      // 0x0698(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch_2;                     // 0x069C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw_2;                       // 0x06A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_299E[0x4];                                     // 0x06A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_4;    // 0x06A8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_2;                // 0x06C0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_299F[0x8];                                     // 0x06D8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             CallFunc_MakeTransform_ReturnValue;                // 0x06E0(0x0060)(IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0740(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AGrannyPugalka_C*                       CallFunc_FinishSpawningActor_ReturnValue;          // 0x0748(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_5;    // 0x0750(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_FindLookAtRotation_ReturnValue_2;         // 0x0768(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FRotator                               CallFunc_SelectRotator_ReturnValue;                // 0x0780(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0798(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBlendableInterface>   CallFunc_AddOrUpdateBlendable_InBlendableObject_CastInput; // 0x07A0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue_1; // 0x07B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IBlendableInterface>   CallFunc_AddOrUpdateBlendable_InBlendableObject_CastInput_1; // 0x07B8(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
	class APlayerCameraManager*                   CallFunc_GetPlayerCameraManager_ReturnValue_1;     // 0x07C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ULegacyCameraShake*                     CallFunc_StartLegacyCameraShake_ReturnValue_1;     // 0x07D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue_1;         // 0x07D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_IsClosed_Variable_1;                     // 0x07E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x07E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29A0[0x6];                                     // 0x07E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ABlockingVolume*>                CallFunc_GetAllActorsOfClass_OutActors;            // 0x07E8(0x0010)(ReferenceParm)
	class ABlockingVolume*                        CallFunc_Array_Get_Item_2;                         // 0x07F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0800(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0804(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29A1[0x3];                                     // 0x0805(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_VSize_ReturnValue;                        // 0x0808(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_MapRangeClamped_ReturnValue;              // 0x0810(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0818(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29A2[0x3];                                     // 0x0819(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_BoolToInt_ReturnValue;               // 0x081C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Conv_IntToFloat_ReturnValue;              // 0x0820(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29A3[0x4];                                     // 0x0824(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0828(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0840(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0848(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingle_OutHit;                   // 0x0860(0x00E8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingle_ReturnValue;              // 0x0948(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsFalling_ReturnValue;                    // 0x0949(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPhysicalSurface                              CallFunc_GetSurfaceType_ReturnValue;               // 0x094A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x094B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29A4[0x4];                                     // 0x094C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             K2Node_Select_Default_2;                           // 0x0950(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue;           // 0x0958(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X;                            // 0x0960(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x0968(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x0970(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_1;                          // 0x0978(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_1;                          // 0x0980(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_1;                          // 0x0988(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue;                   // 0x0990(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_MakeVector_ReturnValue_1;                 // 0x09A8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_VSize_ReturnValue_1;                      // 0x09C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_VSize_ReturnValue_2;                      // 0x09C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_MapRangeClamped_ReturnValue_1;            // 0x09D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x09D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x09D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29A5[0x2];                                     // 0x09DA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_AddMovementInput_ScaleValue_ImplicitCast; // 0x09DC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_AddMovementInput_ScaleValue_ImplicitCast_1; // 0x09E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29A6[0x4];                                     // 0x09E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Lerp_Alpha_ImplicitCast;                  // 0x09E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetCurrentFocalLength_InFocalLength_ImplicitCast; // 0x09F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29A7[0x4];                                     // 0x09F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SetDoublePropertyByName_Value_ImplicitCast; // 0x09F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_SetDoublePropertyByName_Value_ImplicitCast_1; // 0x0A00(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetPitchMultiplier_NewPitchMultiplier_ImplicitCast; // 0x0A08(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetPitchMultiplier_NewPitchMultiplier_ImplicitCast_1; // 0x0A0C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Delay_Duration_ImplicitCast;              // 0x0A10(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29A8[0x4];                                     // 0x0A14(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0A18(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SpawnSoundAttached_VolumeMultiplier_ImplicitCast; // 0x0A20(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Delay_Duration_ImplicitCast_1;            // 0x0A24(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn) == 0x000010, "Wrong alignment on BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn");
static_assert(sizeof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn) == 0x000A30, "Wrong size on BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, EntryPoint) == 0x000000, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_struct_Variable) == 0x000008, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_byte_Variable) == 0x000018, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakVector2D_X) == 0x000020, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakVector2D_X' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakVector2D_Y) == 0x000028, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakVector2D_Y' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_byte_Variable_1) == 0x000030, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_MakeVector2D_ReturnValue) == 0x000038, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_SelectFloat_ReturnValue) == 0x000048, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_SelectFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_SelectFloat_ReturnValue_1) == 0x000050, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_SelectFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Create_ReturnValue) == 0x000058, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Create_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_MakeStruct_Margin) == 0x000060, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_MakeStruct_Margin' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_CreateDelegate_OutputDelegate) == 0x000070, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Create_ReturnValue_1) == 0x000080, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Create_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_CreateDelegate_OutputDelegate_1) == 0x000088, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_CreateDelegate_OutputDelegate_2) == 0x000098, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Create_ReturnValue_2) == 0x0000A8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Create_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Lerp_ReturnValue) == 0x0000B0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Lerp_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_EnhancedInputActionEvent_ActionValue) == 0x0000B8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_EnhancedInputActionEvent_ActionValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_EnhancedInputActionEvent_ElapsedTime) == 0x0000D8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_EnhancedInputActionEvent_ElapsedTime' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_EnhancedInputActionEvent_TriggeredTime) == 0x0000DC, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_EnhancedInputActionEvent_TriggeredTime' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_EnhancedInputActionEvent_SourceAction) == 0x0000E0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_EnhancedInputActionEvent_SourceAction' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_object_Variable) == 0x0000E8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Conv_InputActionValueToBool_ReturnValue) == 0x0000F0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Conv_InputActionValueToBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_real_Variable) == 0x0000F8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_real_Variable' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_real_Variable_1) == 0x000100, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_real_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_real_Variable_0) == 0x000108, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_real_Variable_0' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_real_Variable_1_0) == 0x000110, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_real_Variable_1_0' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_bool_Variable) == 0x000118, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_struct_Variable_1) == 0x000120, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_struct_Variable_2) == 0x000180, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_struct_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_AddComponent_ReturnValue) == 0x0001E0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_AddComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_AddComponent_ReturnValue_1) == 0x0001E8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_AddComponent_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_CreateDelegate_OutputDelegate_3) == 0x0001F0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_struct_Variable_3) == 0x000200, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_struct_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_CreateDelegate_OutputDelegate_4) == 0x000260, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000270, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_AddComponent_ReturnValue_2) == 0x000278, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_AddComponent_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Create_ReturnValue_3) == 0x000280, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Create_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_byte_Variable_2) == 0x000288, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_object_Variable_1) == 0x000290, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_object_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_object_Variable_2) == 0x000298, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_object_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_object_Variable_3) == 0x0002A0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_object_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_object_Variable_4) == 0x0002A8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_object_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_object_Variable_5) == 0x0002B0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_object_Variable_5' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_object_Variable_6) == 0x0002B8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_object_Variable_6' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_bool_Variable_1) == 0x0002C8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_text_Variable) == 0x0002D0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Not_PreBool_ReturnValue) == 0x0002E8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_bool_Has_Been_Initd_Variable) == 0x0002E9, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_bool_Has_Been_Initd_Variable' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_bool_IsClosed_Variable) == 0x0002EA, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_bool_IsClosed_Variable' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_int_Loop_Counter_Variable) == 0x0002EC, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Add_IntInt_ReturnValue) == 0x0002F0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_int_Array_Index_Variable) == 0x0002F4, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_real_Variable_2) == 0x0002F8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_real_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetControlRotation_ReturnValue) == 0x000300, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetControlRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetControlRotation_ReturnValue_1) == 0x000318, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetControlRotation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakRotator_Roll) == 0x000330, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakRotator_Roll' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakRotator_Pitch) == 0x000334, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakRotator_Pitch' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakRotator_Yaw) == 0x000338, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakRotator_Yaw' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakRotator_Roll_1) == 0x00033C, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakRotator_Roll_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakRotator_Pitch_1) == 0x000340, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakRotator_Pitch_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakRotator_Yaw_1) == 0x000344, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakRotator_Yaw_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_MakeRotator_ReturnValue) == 0x000348, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_MakeRotator_ReturnValue_1) == 0x000360, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_MakeRotator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetForwardVector_ReturnValue) == 0x000378, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetForwardVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetRightVector_ReturnValue) == 0x000390, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetRightVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_text_Variable_1) == 0x0003A8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_real_Variable_3) == 0x0003C0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_real_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_object_Variable_7) == 0x0003C8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_object_Variable_7' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetControlRotation_ReturnValue_2) == 0x0003D0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetControlRotation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetRightVector_ReturnValue_1) == 0x0003E8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetRightVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Conv_RotatorToVector_ReturnValue) == 0x000400, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Conv_RotatorToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_Event_DeltaSeconds) == 0x000418, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_Select_Default) == 0x000420, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_Select_Default_1) == 0x000438, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetPlayerController_ReturnValue) == 0x000450, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetHUD_ReturnValue) == 0x000458, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetHUD_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_AddChildToStackBox_ReturnValue) == 0x000460, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_AddChildToStackBox_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_DynamicCast_AsBP_Granny_HUD) == 0x000468, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_DynamicCast_AsBP_Granny_HUD' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_DynamicCast_bSuccess) == 0x000470, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_CustomEvent_Text) == 0x000478, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_CustomEvent_Text' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_AddChildToStackBox_ReturnValue_1) == 0x000480, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_AddChildToStackBox_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_text_Variable_2) == 0x000488, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_text_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_EnhancedInputActionEvent_ActionValue_1) == 0x0004A0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_EnhancedInputActionEvent_ActionValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_EnhancedInputActionEvent_ElapsedTime_1) == 0x0004C0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_EnhancedInputActionEvent_ElapsedTime_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_EnhancedInputActionEvent_TriggeredTime_1) == 0x0004C4, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_EnhancedInputActionEvent_TriggeredTime_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_EnhancedInputActionEvent_SourceAction_1) == 0x0004C8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_EnhancedInputActionEvent_SourceAction_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_real_Variable_3_0) == 0x0004D0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_real_Variable_3_0' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_real_Variable_2_0) == 0x0004D8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_real_Variable_2_0' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Conv_InputActionValueToAxis2D_ReturnValue) == 0x0004E0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Conv_InputActionValueToAxis2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_text_Variable_3) == 0x0004F0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_text_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_CustomEvent_Zoom) == 0x000508, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_CustomEvent_Zoom' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_RandomFloatInRange_ReturnValue) == 0x000510, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_text_Variable_4) == 0x000518, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_text_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetAllActorsOfClassWithTag_OutActors) == 0x000530, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetAllActorsOfClassWithTag_OutActors' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Array_Get_Item) == 0x000540, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_CustomEvent_OverlappedActor) == 0x000548, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_CustomEvent_OverlappedActor' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_CustomEvent_OtherActor) == 0x000550, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_CustomEvent_OtherActor' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetAllActorsOfClassWithTag_OutActors_1) == 0x000558, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetAllActorsOfClassWithTag_OutActors_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000568, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Array_Get_Item_1) == 0x000570, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000578, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetController_ReturnValue) == 0x000590, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000598, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_FindLookAtRotation_ReturnValue) == 0x0005B0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_FindLookAtRotation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetController_ReturnValue_1) == 0x0005C8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetPlayerController_ReturnValue_1) == 0x0005D0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetPlayerController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_DynamicCast_AsBP_Granny_Controller) == 0x0005D8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_DynamicCast_AsBP_Granny_Controller' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_DynamicCast_bSuccess_1) == 0x0005E0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetHUD_ReturnValue_1) == 0x0005E8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetHUD_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_DynamicCast_AsBP_Granny_HUD_1) == 0x0005F0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_DynamicCast_AsBP_Granny_HUD_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_DynamicCast_bSuccess_2) == 0x0005F8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetPlayerCameraManager_ReturnValue) == 0x000600, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetPlayerCameraManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_StartLegacyCameraShake_ReturnValue) == 0x000608, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_StartLegacyCameraShake_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetPlayerController_ReturnValue_2) == 0x000610, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetPlayerController_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetHUD_ReturnValue_2) == 0x000618, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetHUD_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_bool_Has_Been_Initd_Variable_1) == 0x000620, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_bool_Has_Been_Initd_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_DynamicCast_AsBP_Granny_HUD_2) == 0x000628, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_DynamicCast_AsBP_Granny_HUD_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_DynamicCast_bSuccess_3) == 0x000630, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x000638, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_K2_GetComponentLocation_ReturnValue_2) == 0x000650, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_K2_GetComponentLocation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_K2_GetComponentLocation_ReturnValue_3) == 0x000668, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_K2_GetComponentLocation_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_FindLookAtRotation_ReturnValue_1) == 0x000680, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_FindLookAtRotation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakRotator_Roll_2) == 0x000698, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakRotator_Roll_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakRotator_Pitch_2) == 0x00069C, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakRotator_Pitch_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakRotator_Yaw_2) == 0x0006A0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakRotator_Yaw_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_K2_GetComponentLocation_ReturnValue_4) == 0x0006A8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_K2_GetComponentLocation_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_MakeRotator_ReturnValue_2) == 0x0006C0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_MakeRotator_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_MakeTransform_ReturnValue) == 0x0006E0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_MakeTransform_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue) == 0x000740, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_FinishSpawningActor_ReturnValue) == 0x000748, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_FinishSpawningActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_K2_GetComponentLocation_ReturnValue_5) == 0x000750, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_K2_GetComponentLocation_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_FindLookAtRotation_ReturnValue_2) == 0x000768, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_FindLookAtRotation_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_SelectRotator_ReturnValue) == 0x000780, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_SelectRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_CreateDynamicMaterialInstance_ReturnValue) == 0x000798, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_CreateDynamicMaterialInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_AddOrUpdateBlendable_InBlendableObject_CastInput) == 0x0007A0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_AddOrUpdateBlendable_InBlendableObject_CastInput' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_CreateDynamicMaterialInstance_ReturnValue_1) == 0x0007B0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_CreateDynamicMaterialInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_AddOrUpdateBlendable_InBlendableObject_CastInput_1) == 0x0007B8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_AddOrUpdateBlendable_InBlendableObject_CastInput_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetPlayerCameraManager_ReturnValue_1) == 0x0007C8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetPlayerCameraManager_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_StartLegacyCameraShake_ReturnValue_1) == 0x0007D0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_StartLegacyCameraShake_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_RandomFloatInRange_ReturnValue_1) == 0x0007D8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_RandomFloatInRange_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, Temp_bool_IsClosed_Variable_1) == 0x0007E0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::Temp_bool_IsClosed_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_IsValid_ReturnValue) == 0x0007E1, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetAllActorsOfClass_OutActors) == 0x0007E8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Array_Get_Item_2) == 0x0007F8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Array_Length_ReturnValue) == 0x000800, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Less_IntInt_ReturnValue) == 0x000804, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_VSize_ReturnValue) == 0x000808, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_MapRangeClamped_ReturnValue) == 0x000810, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_MapRangeClamped_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000818, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Conv_BoolToInt_ReturnValue) == 0x00081C, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Conv_BoolToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Conv_IntToFloat_ReturnValue) == 0x000820, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Conv_IntToFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000828, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000840, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Subtract_VectorVector_ReturnValue) == 0x000848, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_LineTraceSingle_OutHit) == 0x000860, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_LineTraceSingle_OutHit' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_LineTraceSingle_ReturnValue) == 0x000948, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_LineTraceSingle_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_IsFalling_ReturnValue) == 0x000949, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_IsFalling_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_GetSurfaceType_ReturnValue) == 0x00094A, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_GetSurfaceType_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Not_PreBool_ReturnValue_1) == 0x00094B, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Not_PreBool_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, K2Node_Select_Default_2) == 0x000950, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_SpawnSoundAttached_ReturnValue) == 0x000958, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_SpawnSoundAttached_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakVector_X) == 0x000960, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakVector_Y) == 0x000968, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakVector_Z) == 0x000970, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakVector_X_1) == 0x000978, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakVector_Y_1) == 0x000980, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BreakVector_Z_1) == 0x000988, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_MakeVector_ReturnValue) == 0x000990, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_MakeVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_MakeVector_ReturnValue_1) == 0x0009A8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_MakeVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_VSize_ReturnValue_1) == 0x0009C0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_VSize_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_VSize_ReturnValue_2) == 0x0009C8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_VSize_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_MapRangeClamped_ReturnValue_1) == 0x0009D0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_MapRangeClamped_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Greater_DoubleDouble_ReturnValue) == 0x0009D8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Greater_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_BooleanAND_ReturnValue) == 0x0009D9, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_AddMovementInput_ScaleValue_ImplicitCast) == 0x0009DC, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_AddMovementInput_ScaleValue_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_AddMovementInput_ScaleValue_ImplicitCast_1) == 0x0009E0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_AddMovementInput_ScaleValue_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Lerp_Alpha_ImplicitCast) == 0x0009E8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Lerp_Alpha_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_SetCurrentFocalLength_InFocalLength_ImplicitCast) == 0x0009F0, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_SetCurrentFocalLength_InFocalLength_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_SetDoublePropertyByName_Value_ImplicitCast) == 0x0009F8, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_SetDoublePropertyByName_Value_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_SetDoublePropertyByName_Value_ImplicitCast_1) == 0x000A00, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_SetDoublePropertyByName_Value_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_SetPitchMultiplier_NewPitchMultiplier_ImplicitCast) == 0x000A08, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_SetPitchMultiplier_NewPitchMultiplier_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_SetPitchMultiplier_NewPitchMultiplier_ImplicitCast_1) == 0x000A0C, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_SetPitchMultiplier_NewPitchMultiplier_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Delay_Duration_ImplicitCast) == 0x000A10, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Delay_Duration_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x000A18, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_SpawnSoundAttached_VolumeMultiplier_ImplicitCast) == 0x000A20, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_SpawnSoundAttached_VolumeMultiplier_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn, CallFunc_Delay_Duration_ImplicitCast_1) == 0x000A24, "Member 'BP_CinematicPawn_C_ExecuteUbergraph_BP_CinematicPawn::CallFunc_Delay_Duration_ImplicitCast_1' has a wrong offset!");

// Function BP_CinematicPawn.BP_CinematicPawn_C.CameraShake
// 0x0028 (0x0028 - 0x0000)
struct BP_CinematicPawn_C_CameraShake final
{
public:
	class APlayerCameraManager*                   CallFunc_GetPlayerCameraManager_ReturnValue;       // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_VSize_ReturnValue;                        // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_MapRangeClamped_ReturnValue;              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ULegacyCameraShake*                     CallFunc_StartLegacyCameraShake_ReturnValue;       // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_StartLegacyCameraShake_Scale_ImplicitCast; // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_CinematicPawn_C_CameraShake) == 0x000008, "Wrong alignment on BP_CinematicPawn_C_CameraShake");
static_assert(sizeof(BP_CinematicPawn_C_CameraShake) == 0x000028, "Wrong size on BP_CinematicPawn_C_CameraShake");
static_assert(offsetof(BP_CinematicPawn_C_CameraShake, CallFunc_GetPlayerCameraManager_ReturnValue) == 0x000000, "Member 'BP_CinematicPawn_C_CameraShake::CallFunc_GetPlayerCameraManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_CameraShake, CallFunc_VSize_ReturnValue) == 0x000008, "Member 'BP_CinematicPawn_C_CameraShake::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_CameraShake, CallFunc_MapRangeClamped_ReturnValue) == 0x000010, "Member 'BP_CinematicPawn_C_CameraShake::CallFunc_MapRangeClamped_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_CameraShake, CallFunc_StartLegacyCameraShake_ReturnValue) == 0x000018, "Member 'BP_CinematicPawn_C_CameraShake::CallFunc_StartLegacyCameraShake_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_CinematicPawn_C_CameraShake, CallFunc_StartLegacyCameraShake_Scale_ImplicitCast) == 0x000020, "Member 'BP_CinematicPawn_C_CameraShake::CallFunc_StartLegacyCameraShake_Scale_ImplicitCast' has a wrong offset!");

}

