#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DuctTape

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ItemBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DuctTape.BP_DuctTape_C
// 0x0010 (0x0400 - 0x03F0)
class ABP_DuctTape_C final : public ABP_ItemBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_DuctTape_C;                      // 0x03F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void TeleportToSafeLocation();
	void Taken(bool ByGranny);
	void ExecuteUbergraph_BP_DuctTape(int32 EntryPoint);
	void CalcSafeLocation();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_DuctTape_C">();
	}
	static class ABP_DuctTape_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DuctTape_C>();
	}
};
static_assert(alignof(ABP_DuctTape_C) == 0x000010, "Wrong alignment on ABP_DuctTape_C");
static_assert(sizeof(ABP_DuctTape_C) == 0x000400, "Wrong size on ABP_DuctTape_C");
static_assert(offsetof(ABP_DuctTape_C, UberGraphFrame_BP_DuctTape_C) == 0x0003F0, "Member 'ABP_DuctTape_C::UberGraphFrame_BP_DuctTape_C' has a wrong offset!");

}

