#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ExtraLock

#include "Basic.hpp"

#include "BP_ExtraLock_classes.hpp"
#include "BP_ExtraLock_parameters.hpp"


namespace SDK
{

// Function BP_ExtraLock.BP_ExtraLock_C.Timeline__UpdateFunc
// (BlueprintEvent)

void ABP_ExtraLock_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ExtraLock_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ExtraLock.BP_ExtraLock_C.Timeline__FinishedFunc
// (BlueprintEvent)

void ABP_ExtraLock_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ExtraLock_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ExtraLock.BP_ExtraLock_C.Interact
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Player_C*                     Param_Player                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       Hit                                                    (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_ExtraLock_C::Interact(class ABP_Player_C* Param_Player, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ExtraLock_C", "Interact");

	Params::BP_ExtraLock_C_Interact Parms{};

	Parms.Param_Player = Param_Player;
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ExtraLock.BP_ExtraLock_C.GetAllNotUnscrewed
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class UStaticMeshComponent*>     NewLocalVar1                                           (Parm, OutParm, ContainsInstancedReference)

void ABP_ExtraLock_C::GetAllNotUnscrewed(TArray<class UStaticMeshComponent*>* NewLocalVar1)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ExtraLock_C", "GetAllNotUnscrewed");

	Params::BP_ExtraLock_C_GetAllNotUnscrewed Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewLocalVar1 != nullptr)
		*NewLocalVar1 = std::move(Parms.NewLocalVar1);
}


// Function BP_ExtraLock.BP_ExtraLock_C.ExecuteUbergraph_BP_ExtraLock
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ExtraLock_C::ExecuteUbergraph_BP_ExtraLock(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ExtraLock_C", "ExecuteUbergraph_BP_ExtraLock");

	Params::BP_ExtraLock_C_ExecuteUbergraph_BP_ExtraLock Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

