#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Granny

#include "Basic.hpp"

#include "BP_Granny_classes.hpp"
#include "BP_Granny_parameters.hpp"


namespace SDK
{

// Function BP_Granny.BP_Granny_C.UIGEvyFEABHKFUEH
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::UIGEvyFEABHKFUEH()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "UIGEvyFEABHKFUEH");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.Timeline__UpdateFunc
// (BlueprintEvent)

void ABP_Granny_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.Timeline__FinishedFunc
// (BlueprintEvent)

void ABP_Granny_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.Timeline_1__UpdateFunc
// (BlueprintEvent)

void ABP_Granny_C::Timeline_1__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "Timeline_1__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.Timeline_1__FinishedFunc
// (BlueprintEvent)

void ABP_Granny_C::Timeline_1__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "Timeline_1__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.Timeline_0__UpdateFunc
// (BlueprintEvent)

void ABP_Granny_C::Timeline_0__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "Timeline_0__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.Timeline_0__FinishedFunc
// (BlueprintEvent)

void ABP_Granny_C::Timeline_0__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "Timeline_0__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.ThrowMyItems
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::ThrowMyItems()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "ThrowMyItems");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.TasksDebug
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::TasksDebug()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "TasksDebug");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.TaskComplete_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FST_Task                         Task                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::TaskComplete_Event(const struct FST_Task& Task)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "TaskComplete_Event");

	Params::BP_Granny_C_TaskComplete_Event Parms{};

	Parms.Task = std::move(Task);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Granny.BP_Granny_C.StartNoiseSeeking
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          NoiseLocation                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::StartNoiseSeeking(const struct FVector& NoiseLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "StartNoiseSeeking");

	Params::BP_Granny_C_StartNoiseSeeking Parms{};

	Parms.NoiseLocation = std::move(NoiseLocation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Granny.BP_Granny_C.ShowEyes
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::ShowEyes()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "ShowEyes");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.SenseCamera
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::SenseCamera()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "SenseCamera");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.SelectTask
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::SelectTask()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "SelectTask");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.Screamer
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::Screamer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "Screamer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "ReceiveTick");

	Params::BP_Granny_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Granny.BP_Granny_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_Granny_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Granny_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.RandomEyeDerg
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::RandomEyeDerg()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "RandomEyeDerg");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.PlayAngryMorph
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::PlayAngryMorph()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "PlayAngryMorph");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.OpenDoor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::OpenDoor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "OpenDoor");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.OnSuccess_E8896B7E4F9BD749C50E528AB02748E9
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::OnSuccess_E8896B7E4F9BD749C50E528AB02748E9(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "OnSuccess_E8896B7E4F9BD749C50E528AB02748E9");

	Params::BP_Granny_C_OnSuccess_E8896B7E4F9BD749C50E528AB02748E9 Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Granny.BP_Granny_C.OnSuccess_77A6E78F4B82EDA58966EA84452C11C8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::OnSuccess_77A6E78F4B82EDA58966EA84452C11C8(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "OnSuccess_77A6E78F4B82EDA58966EA84452C11C8");

	Params::BP_Granny_C_OnSuccess_77A6E78F4B82EDA58966EA84452C11C8 Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Granny.BP_Granny_C.OnSuccess_6C2D868343FB20CA9ED08CABE6031AA2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::OnSuccess_6C2D868343FB20CA9ED08CABE6031AA2(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "OnSuccess_6C2D868343FB20CA9ED08CABE6031AA2");

	Params::BP_Granny_C_OnSuccess_6C2D868343FB20CA9ED08CABE6031AA2 Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Granny.BP_Granny_C.OnFail_E8896B7E4F9BD749C50E528AB02748E9
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::OnFail_E8896B7E4F9BD749C50E528AB02748E9(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "OnFail_E8896B7E4F9BD749C50E528AB02748E9");

	Params::BP_Granny_C_OnFail_E8896B7E4F9BD749C50E528AB02748E9 Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Granny.BP_Granny_C.OnFail_77A6E78F4B82EDA58966EA84452C11C8
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::OnFail_77A6E78F4B82EDA58966EA84452C11C8(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "OnFail_77A6E78F4B82EDA58966EA84452C11C8");

	Params::BP_Granny_C_OnFail_77A6E78F4B82EDA58966EA84452C11C8 Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Granny.BP_Granny_C.OnFail_6C2D868343FB20CA9ED08CABE6031AA2
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EPathFollowingResult                    MovementResult                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::OnFail_6C2D868343FB20CA9ED08CABE6031AA2(EPathFollowingResult MovementResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "OnFail_6C2D868343FB20CA9ED08CABE6031AA2");

	Params::BP_Granny_C_OnFail_6C2D868343FB20CA9ED08CABE6031AA2 Parms{};

	Parms.MovementResult = MovementResult;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Granny.BP_Granny_C.NightmareImprovements
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::NightmareImprovements()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "NightmareImprovements");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.NearTheGoodTrapPoint
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    GoodPlace                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::NearTheGoodTrapPoint(bool* GoodPlace)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "NearTheGoodTrapPoint");

	Params::BP_Granny_C_NearTheGoodTrapPoint Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (GoodPlace != nullptr)
		*GoodPlace = Parms.GoodPlace;
}


// Function BP_Granny.BP_Granny_C.NAUJIFENIFU
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::NAUJIFENIFU()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "NAUJIFENIFU");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.MakeTrap
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::MakeTrap()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "MakeTrap");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.ihbfdsbjnfds
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::Ihbfdsbjnfds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "ihbfdsbjnfds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.Herobrinize
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::Herobrinize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "Herobrinize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.HeadAnimation
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::HeadAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "HeadAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.GrannySeePlayer
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Player_C*                     Param_Player                                           (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    See                                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::GrannySeePlayer(class ABP_Player_C** Param_Player, bool* See)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "GrannySeePlayer");

	Params::BP_Granny_C_GrannySeePlayer Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_Player != nullptr)
		*Param_Player = Parms.Param_Player;

	if (See != nullptr)
		*See = Parms.See;
}


// Function BP_Granny.BP_Granny_C.GetSenseStrength
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ReturnValue1                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ReturnValue2                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

double ABP_Granny_C::GetSenseStrength(float* ReturnValue1, float* ReturnValue2)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "GetSenseStrength");

	Params::BP_Granny_C_GetSenseStrength Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ReturnValue1 != nullptr)
		*ReturnValue1 = Parms.ReturnValue1;

	if (ReturnValue2 != nullptr)
		*ReturnValue2 = Parms.ReturnValue2;

	return Parms.ReturnValue;
}


// Function BP_Granny.BP_Granny_C.GetRandomPointInTorus
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FVector                          Param_Center                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Up                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Forward                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  TorusRadius                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  TorusThikness                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Angle                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Subdivisions                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Point                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::GetRandomPointInTorus(const struct FVector& Param_Center, const struct FVector& Up, const struct FVector& Forward, double TorusRadius, double TorusThikness, double Angle, int32 Subdivisions, struct FVector* Point)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "GetRandomPointInTorus");

	Params::BP_Granny_C_GetRandomPointInTorus Parms{};

	Parms.Param_Center = std::move(Param_Center);
	Parms.Up = std::move(Up);
	Parms.Forward = std::move(Forward);
	Parms.TorusRadius = TorusRadius;
	Parms.TorusThikness = TorusThikness;
	Parms.Angle = Angle;
	Parms.Subdivisions = Subdivisions;

	UObject::ProcessEvent(Func, &Parms);

	if (Point != nullptr)
		*Point = std::move(Parms.Point);
}


// Function BP_Granny.BP_Granny_C.GetRandomIdlePoint
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FName                             Tag                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Vector                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::GetRandomIdlePoint(class FName Tag, struct FVector* Vector)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "GetRandomIdlePoint");

	Params::BP_Granny_C_GetRandomIdlePoint Parms{};

	Parms.Tag = Tag;

	UObject::ProcessEvent(Func, &Parms);

	if (Vector != nullptr)
		*Vector = std::move(Parms.Vector);
}


// Function BP_Granny.BP_Granny_C.GetNearbyRoom
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FVector                          V2                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Output                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::GetNearbyRoom(const struct FVector& V2, struct FVector* Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "GetNearbyRoom");

	Params::BP_Granny_C_GetNearbyRoom Parms{};

	Parms.V2 = std::move(V2);

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = std::move(Parms.Output);
}


// Function BP_Granny.BP_Granny_C.GetBestTaskId
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<struct FST_Task>                 Array                                                  (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// int32                                   Param_Index                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::GetBestTaskId(TArray<struct FST_Task>& Array, int32* Param_Index)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "GetBestTaskId");

	Params::BP_Granny_C_GetBestTaskId Parms{};

	Parms.Array = std::move(Array);

	UObject::ProcessEvent(Func, &Parms);

	Array = std::move(Parms.Array);

	if (Param_Index != nullptr)
		*Param_Index = Parms.Param_Index;
}


// Function BP_Granny.BP_Granny_C.GetAllTasks
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FST_Task>                 Param_Tasks                                            (Parm, OutParm)

void ABP_Granny_C::GetAllTasks(TArray<struct FST_Task>* Param_Tasks)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "GetAllTasks");

	Params::BP_Granny_C_GetAllTasks Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Param_Tasks != nullptr)
		*Param_Tasks = std::move(Parms.Param_Tasks);
}


// Function BP_Granny.BP_Granny_C.Get Nearby Predict Spline
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FVector                          V2                                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Location                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AAiPredictFlow_C*                 Flow                                                   (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::Get_Nearby_Predict_Spline(const struct FVector& V2, struct FVector* Location, class AAiPredictFlow_C** Flow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "Get Nearby Predict Spline");

	Params::BP_Granny_C_Get_Nearby_Predict_Spline Parms{};

	Parms.V2 = std::move(V2);

	UObject::ProcessEvent(Func, &Parms);

	if (Location != nullptr)
		*Location = std::move(Parms.Location);

	if (Flow != nullptr)
		*Flow = Parms.Flow;
}


// Function BP_Granny.BP_Granny_C.Footstep
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::Footstep()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "Footstep");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.fg
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::Fg()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "fg");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.ExecuteUbergraph_BP_Granny
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::ExecuteUbergraph_BP_Granny(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "ExecuteUbergraph_BP_Granny");

	Params::BP_Granny_C_ExecuteUbergraph_BP_Granny Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Granny.BP_Granny_C.DrawNoises
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector                          Param_Center                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::DrawNoises(const struct FVector& Param_Center)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "DrawNoises");

	Params::BP_Granny_C_DrawNoises Parms{};

	Parms.Param_Center = std::move(Param_Center);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Granny.BP_Granny_C.CheckDistanceToPlayer
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::CheckDistanceToPlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "CheckDistanceToPlayer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.CatchPlayer
// (BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::CatchPlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "CatchPlayer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.CameraSetup
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Granny_C::CameraSetup()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "CameraSetup");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Granny.BP_Granny_C.BndEvt__BP_Granny_Sphere_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_Granny_C::BndEvt__BP_Granny_Sphere_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "BndEvt__BP_Granny_Sphere_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_Granny_C_BndEvt__BP_Granny_Sphere_K2Node_ComponentBoundEvent_1_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Granny.BP_Granny_C.AiHasTask
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FName                             TaskTag                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Return                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::AiHasTask(class FName TaskTag, bool* Return)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "AiHasTask");

	Params::BP_Granny_C_AiHasTask Parms{};

	Parms.TaskTag = TaskTag;

	UObject::ProcessEvent(Func, &Parms);

	if (Return != nullptr)
		*Return = Parms.Return;
}


// Function BP_Granny.BP_Granny_C.AddTask
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Task_Name                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Task_Weight                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Task_Time_Limit                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Disposable                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Granny_C::AddTask(class FName Task_Name, double Task_Weight, double Task_Time_Limit, bool Disposable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Granny_C", "AddTask");

	Params::BP_Granny_C_AddTask Parms{};

	Parms.Task_Name = Task_Name;
	Parms.Task_Weight = Task_Weight;
	Parms.Task_Time_Limit = Task_Time_Limit;
	Parms.Disposable = Disposable;

	UObject::ProcessEvent(Func, &Parms);
}

}

