#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GrannyHUD

#include "Basic.hpp"

#include "BP_GrannyHUD_classes.hpp"
#include "BP_GrannyHUD_parameters.hpp"


namespace SDK
{

// Function BP_GrannyHUD.BP_GrannyHUD_C.ToggleMenu
// (BlueprintCallable, BlueprintEvent)

void ABP_GrannyHUD_C::ToggleMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GrannyHUD_C", "ToggleMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GrannyHUD.BP_GrannyHUD_C.ShowNote
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             NoteText                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void ABP_GrannyHUD_C::ShowNote(const class FText& NoteText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GrannyHUD_C", "ShowNote");

	Params::BP_GrannyHUD_C_ShowNote Parms{};

	Parms.NoteText = std::move(NoteText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GrannyHUD.BP_GrannyHUD_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_GrannyHUD_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GrannyHUD_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_GrannyHUD.BP_GrannyHUD_C.PrintDebugString
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           String                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// bool                                    PrintToLog                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FLinearColor                     Text_Color                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Duration                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GrannyHUD_C::PrintDebugString(const class FString& String, bool PrintToLog, const struct FLinearColor& Text_Color, double Duration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GrannyHUD_C", "PrintDebugString");

	Params::BP_GrannyHUD_C_PrintDebugString Parms{};

	Parms.String = std::move(String);
	Parms.PrintToLog = PrintToLog;
	Parms.Text_Color = std::move(Text_Color);
	Parms.Duration = Duration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GrannyHUD.BP_GrannyHUD_C.ExecuteUbergraph_BP_GrannyHUD
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_GrannyHUD_C::ExecuteUbergraph_BP_GrannyHUD(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GrannyHUD_C", "ExecuteUbergraph_BP_GrannyHUD");

	Params::BP_GrannyHUD_C_ExecuteUbergraph_BP_GrannyHUD Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_GrannyHUD.BP_GrannyHUD_C.CallNotification
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             WriteText                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void ABP_GrannyHUD_C::CallNotification(const class FText& WriteText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_GrannyHUD_C", "CallNotification");

	Params::BP_GrannyHUD_C_CallNotification Parms{};

	Parms.WriteText = std::move(WriteText);

	UObject::ProcessEvent(Func, &Parms);
}

}

