#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HideBase

#include "Basic.hpp"

#include "BP_HideBase_classes.hpp"
#include "BP_HideBase_parameters.hpp"


namespace SDK
{

// Function BP_HideBase.BP_HideBase_C.UNHIDE
// (BlueprintCallable, BlueprintEvent)

void ABP_HideBase_C::UNHIDE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HideBase_C", "UNHIDE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HideBase.BP_HideBase_C.Interact
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Player_C*                     Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       Hit                                                    (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_HideBase_C::Interact(class ABP_Player_C* Player, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HideBase_C", "Interact");

	Params::BP_HideBase_C_Interact Parms{};

	Parms.Player = Player;
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HideBase.BP_HideBase_C.HideAnimFinished_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    PlayerHide                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HideBase_C::HideAnimFinished_Event(bool PlayerHide)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HideBase_C", "HideAnimFinished_Event");

	Params::BP_HideBase_C_HideAnimFinished_Event Parms{};

	Parms.PlayerHide = PlayerHide;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HideBase.BP_HideBase_C.GetGranny
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ABP_Granny_C*                     Granny                                                 (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_HideBase_C::GetGranny(class ABP_Granny_C** Granny)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HideBase_C", "GetGranny");

	Params::BP_HideBase_C_GetGranny Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Granny != nullptr)
		*Granny = Parms.Granny;
}


// Function BP_HideBase.BP_HideBase_C.ExecuteUbergraph_BP_HideBase
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HideBase_C::ExecuteUbergraph_BP_HideBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HideBase_C", "ExecuteUbergraph_BP_HideBase");

	Params::BP_HideBase_C_ExecuteUbergraph_BP_HideBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

