#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LookShake

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LookShake.BP_LookShake_C
// 0x0000 (0x0210 - 0x0210)
class UBP_LookShake_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_LookShake_C">();
	}
	static class UBP_LookShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_LookShake_C>();
	}
};
static_assert(alignof(UBP_LookShake_C) == 0x000010, "Wrong alignment on UBP_LookShake_C");
static_assert(sizeof(UBP_LookShake_C) == 0x000210, "Wrong size on UBP_LookShake_C");

}

