#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MasterKey

#include "Basic.hpp"

#include "BP_MasterKey_classes.hpp"
#include "BP_MasterKey_parameters.hpp"


namespace SDK
{

// Function BP_MasterKey.BP_MasterKey_C.TeleportToSafeLocation
// (BlueprintCallable, BlueprintEvent)

void ABP_MasterKey_C::TeleportToSafeLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterKey_C", "TeleportToSafeLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MasterKey.BP_MasterKey_C.Taken
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ByGranny                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterKey_C::Taken(bool ByGranny)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterKey_C", "Taken");

	Params::BP_MasterKey_C_Taken Parms{};

	Parms.ByGranny = ByGranny;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterKey.BP_MasterKey_C.ExecuteUbergraph_BP_MasterKey
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MasterKey_C::ExecuteUbergraph_BP_MasterKey(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterKey_C", "ExecuteUbergraph_BP_MasterKey");

	Params::BP_MasterKey_C_ExecuteUbergraph_BP_MasterKey Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MasterKey.BP_MasterKey_C.CalcSafeLocation
// (BlueprintCallable, BlueprintEvent)

void ABP_MasterKey_C::CalcSafeLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MasterKey_C", "CalcSafeLocation");

	UObject::ProcessEvent(Func, nullptr);
}

}

