#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PicturePart

#include "Basic.hpp"

#include "BP_PicturePart_classes.hpp"
#include "BP_PicturePart_parameters.hpp"


namespace SDK
{

// Function BP_PicturePart.BP_PicturePart_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_PicturePart_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PicturePart_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PicturePart.BP_PicturePart_C.Use
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Player_C*                     Param_Player                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PicturePart_C::Use(class ABP_Player_C* Param_Player, bool Start)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PicturePart_C", "Use");

	Params::BP_PicturePart_C_Use Parms{};

	Parms.Param_Player = Param_Player;
	Parms.Start = Start;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PicturePart.BP_PicturePart_C.ExecuteUbergraph_BP_PicturePart
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PicturePart_C::ExecuteUbergraph_BP_PicturePart(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PicturePart_C", "ExecuteUbergraph_BP_PicturePart");

	Params::BP_PicturePart_C_ExecuteUbergraph_BP_PicturePart Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

