#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PadlockKey

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ItemBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PadlockKey.BP_PadlockKey_C
// 0x0010 (0x0400 - 0x03F0)
class ABP_PadlockKey_C final : public ABP_ItemBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_PadlockKey_C;                    // 0x03F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void TeleportToSafeLocation();
	void Taken(bool ByGranny);
	void ExecuteUbergraph_BP_PadlockKey(int32 EntryPoint);
	void CalcSafeLocation();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PadlockKey_C">();
	}
	static class ABP_PadlockKey_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PadlockKey_C>();
	}
};
static_assert(alignof(ABP_PadlockKey_C) == 0x000010, "Wrong alignment on ABP_PadlockKey_C");
static_assert(sizeof(ABP_PadlockKey_C) == 0x000400, "Wrong size on ABP_PadlockKey_C");
static_assert(offsetof(ABP_PadlockKey_C, UberGraphFrame_BP_PadlockKey_C) == 0x0003F0, "Member 'ABP_PadlockKey_C::UberGraphFrame_BP_PadlockKey_C' has a wrong offset!");

}

