#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PicturePart

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_ItemBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PicturePart.BP_PicturePart_C
// 0x0010 (0x0400 - 0x03F0)
class ABP_PicturePart_C : public ABP_ItemBase_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_PicturePart_C;                   // 0x03F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         PartNumber;                                        // 0x03F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void Use(class ABP_Player_C* Param_Player, bool Start);
	void ExecuteUbergraph_BP_PicturePart(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PicturePart_C">();
	}
	static class ABP_PicturePart_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PicturePart_C>();
	}
};
static_assert(alignof(ABP_PicturePart_C) == 0x000010, "Wrong alignment on ABP_PicturePart_C");
static_assert(sizeof(ABP_PicturePart_C) == 0x000400, "Wrong size on ABP_PicturePart_C");
static_assert(offsetof(ABP_PicturePart_C, UberGraphFrame_BP_PicturePart_C) == 0x0003F0, "Member 'ABP_PicturePart_C::UberGraphFrame_BP_PicturePart_C' has a wrong offset!");
static_assert(offsetof(ABP_PicturePart_C, PartNumber) == 0x0003F8, "Member 'ABP_PicturePart_C::PartNumber' has a wrong offset!");

}

