#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Pliers

#include "Basic.hpp"

#include "BP_Pliers_classes.hpp"
#include "BP_Pliers_parameters.hpp"


namespace SDK
{

// Function BP_Pliers.BP_Pliers_C.Use
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Player_C*                     Param_Player                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pliers_C::Use(class ABP_Player_C* Param_Player, bool Start)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Pliers_C", "Use");

	Params::BP_Pliers_C_Use Parms{};

	Parms.Param_Player = Param_Player;
	Parms.Start = Start;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pliers.BP_Pliers_C.TeleportToSafeLocation
// (BlueprintCallable, BlueprintEvent)

void ABP_Pliers_C::TeleportToSafeLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Pliers_C", "TeleportToSafeLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Pliers.BP_Pliers_C.Taken
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ByGranny                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pliers_C::Taken(bool ByGranny)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Pliers_C", "Taken");

	Params::BP_Pliers_C_Taken Parms{};

	Parms.ByGranny = ByGranny;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pliers.BP_Pliers_C.ExecuteUbergraph_BP_Pliers
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Pliers_C::ExecuteUbergraph_BP_Pliers(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Pliers_C", "ExecuteUbergraph_BP_Pliers");

	Params::BP_Pliers_C_ExecuteUbergraph_BP_Pliers Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Pliers.BP_Pliers_C.CalcSafeLocation
// (BlueprintCallable, BlueprintEvent)

void ABP_Pliers_C::CalcSafeLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Pliers_C", "CalcSafeLocation");

	UObject::ProcessEvent(Func, nullptr);
}

}

