#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Rock

#include "Basic.hpp"

#include "BP_Rock_classes.hpp"
#include "BP_Rock_parameters.hpp"


namespace SDK
{

// Function BP_Rock.BP_Rock_C.Use
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Player_C*                     Param_Player                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    Start                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rock_C::Use(class ABP_Player_C* Param_Player, bool Start)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rock_C", "Use");

	Params::BP_Rock_C_Use Parms{};

	Parms.Param_Player = Param_Player;
	Parms.Start = Start;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rock.BP_Rock_C.Timeline__UpdateFunc
// (BlueprintEvent)

void ABP_Rock_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rock_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rock.BP_Rock_C.Timeline__FinishedFunc
// (BlueprintEvent)

void ABP_Rock_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rock_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Rock.BP_Rock_C.ExecuteUbergraph_BP_Rock
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Rock_C::ExecuteUbergraph_BP_Rock(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rock_C", "ExecuteUbergraph_BP_Rock");

	Params::BP_Rock_C_ExecuteUbergraph_BP_Rock Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Rock.BP_Rock_C.AddPlayerAnimation
// (BlueprintCallable, BlueprintEvent)

void ABP_Rock_C::AddPlayerAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Rock_C", "AddPlayerAnimation");

	UObject::ProcessEvent(Func, nullptr);
}

}

