#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RemoteDoor

#include "Basic.hpp"

#include "BP_RemoteDoor_classes.hpp"
#include "BP_RemoteDoor_parameters.hpp"


namespace SDK
{

// Function BP_RemoteDoor.BP_RemoteDoor_C.Timeline__UpdateFunc
// (BlueprintEvent)

void ABP_RemoteDoor_C::Timeline__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RemoteDoor_C", "Timeline__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RemoteDoor.BP_RemoteDoor_C.Timeline__FinishedFunc
// (BlueprintEvent)

void ABP_RemoteDoor_C::Timeline__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RemoteDoor_C", "Timeline__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RemoteDoor.BP_RemoteDoor_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_RemoteDoor_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RemoteDoor_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RemoteDoor.BP_RemoteDoor_C.Open
// (BlueprintCallable, BlueprintEvent)

void ABP_RemoteDoor_C::Open()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RemoteDoor_C", "Open");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_RemoteDoor.BP_RemoteDoor_C.Interact
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Player_C*                     Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       Hit                                                    (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_RemoteDoor_C::Interact(class ABP_Player_C* Player, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RemoteDoor_C", "Interact");

	Params::BP_RemoteDoor_C_Interact Parms{};

	Parms.Player = Player;
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RemoteDoor.BP_RemoteDoor_C.ExecuteUbergraph_BP_RemoteDoor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_RemoteDoor_C::ExecuteUbergraph_BP_RemoteDoor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RemoteDoor_C", "ExecuteUbergraph_BP_RemoteDoor");

	Params::BP_RemoteDoor_C_ExecuteUbergraph_BP_RemoteDoor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_RemoteDoor.BP_RemoteDoor_C.ChangeLampColor
// (BlueprintCallable, BlueprintEvent)

void ABP_RemoteDoor_C::ChangeLampColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_RemoteDoor_C", "ChangeLampColor");

	UObject::ProcessEvent(Func, nullptr);
}

}

