#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Screwdriver

#include "Basic.hpp"

#include "BP_Screwdriver_classes.hpp"
#include "BP_Screwdriver_parameters.hpp"


namespace SDK
{

// Function BP_Screwdriver.BP_Screwdriver_C.TeleportToSafeLocation
// (BlueprintCallable, BlueprintEvent)

void ABP_Screwdriver_C::TeleportToSafeLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Screwdriver_C", "TeleportToSafeLocation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Screwdriver.BP_Screwdriver_C.Taken
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ByGranny                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Screwdriver_C::Taken(bool ByGranny)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Screwdriver_C", "Taken");

	Params::BP_Screwdriver_C_Taken Parms{};

	Parms.ByGranny = ByGranny;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Screwdriver.BP_Screwdriver_C.ExecuteUbergraph_BP_Screwdriver
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Screwdriver_C::ExecuteUbergraph_BP_Screwdriver(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Screwdriver_C", "ExecuteUbergraph_BP_Screwdriver");

	Params::BP_Screwdriver_C_ExecuteUbergraph_BP_Screwdriver Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Screwdriver.BP_Screwdriver_C.CalcSafeLocation
// (BlueprintCallable, BlueprintEvent)

void ABP_Screwdriver_C::CalcSafeLocation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Screwdriver_C", "CalcSafeLocation");

	UObject::ProcessEvent(Func, nullptr);
}

}

