#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GrannyStart

#include "Basic.hpp"


namespace SDK::Params
{

// Function GrannyStart.GrannyStart_C.ExecuteUbergraph_GrannyStart
// 0x0004 (0x0004 - 0x0000)
struct GrannyStart_C_ExecuteUbergraph_GrannyStart final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GrannyStart_C_ExecuteUbergraph_GrannyStart) == 0x000004, "Wrong alignment on GrannyStart_C_ExecuteUbergraph_GrannyStart");
static_assert(sizeof(GrannyStart_C_ExecuteUbergraph_GrannyStart) == 0x000004, "Wrong size on GrannyStart_C_ExecuteUbergraph_GrannyStart");
static_assert(offsetof(GrannyStart_C_ExecuteUbergraph_GrannyStart, EntryPoint) == 0x000000, "Member 'GrannyStart_C_ExecuteUbergraph_GrannyStart::EntryPoint' has a wrong offset!");

}

