#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DebugCanvas

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_DebugCanvas.WBP_DebugCanvas_C
// 0x0010 (0x0288 - 0x0278)
class UWBP_DebugCanvas_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0278(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UVerticalBox*                           VerticalBox_0;                                     // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void PrintDebugString(const class FString& String, bool PrintToLog, const struct FLinearColor& Text_Color, double Duration);
	void ExecuteUbergraph_WBP_DebugCanvas(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_DebugCanvas_C">();
	}
	static class UWBP_DebugCanvas_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DebugCanvas_C>();
	}
};
static_assert(alignof(UWBP_DebugCanvas_C) == 0x000008, "Wrong alignment on UWBP_DebugCanvas_C");
static_assert(sizeof(UWBP_DebugCanvas_C) == 0x000288, "Wrong size on UWBP_DebugCanvas_C");
static_assert(offsetof(UWBP_DebugCanvas_C, UberGraphFrame) == 0x000278, "Member 'UWBP_DebugCanvas_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_DebugCanvas_C, VerticalBox_0) == 0x000280, "Member 'UWBP_DebugCanvas_C::VerticalBox_0' has a wrong offset!");

}

