#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_rec_effect

#include "Basic.hpp"

#include "WBP_rec_effect_classes.hpp"
#include "WBP_rec_effect_parameters.hpp"


namespace SDK
{

// Function WBP_rec_effect.WBP_rec_effect_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_rec_effect_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_rec_effect_C", "Tick");

	Params::WBP_rec_effect_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_rec_effect.WBP_rec_effect_C.SliderTextAnim
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_rec_effect_C::SliderTextAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_rec_effect_C", "SliderTextAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_rec_effect.WBP_rec_effect_C.set_time
// (BlueprintCallable, BlueprintEvent)

void UWBP_rec_effect_C::Set_time()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_rec_effect_C", "set_time");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_rec_effect.WBP_rec_effect_C.rec_zoom_effect
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_rec_effect_C::Rec_zoom_effect()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_rec_effect_C", "rec_zoom_effect");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_rec_effect.WBP_rec_effect_C.rec_effect_movement
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_rec_effect_C::Rec_effect_movement()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_rec_effect_C", "rec_effect_movement");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_rec_effect.WBP_rec_effect_C.FPS_GraphAnim
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_rec_effect_C::FPS_GraphAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_rec_effect_C", "FPS_GraphAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_rec_effect.WBP_rec_effect_C.ExecuteUbergraph_WBP_rec_effect
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_rec_effect_C::ExecuteUbergraph_WBP_rec_effect(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_rec_effect_C", "ExecuteUbergraph_WBP_rec_effect");

	Params::WBP_rec_effect_C_ExecuteUbergraph_WBP_rec_effect Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_rec_effect.WBP_rec_effect_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_rec_effect_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_rec_effect_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_rec_effect.WBP_rec_effect_C.BaseCasts
// (BlueprintCallable, BlueprintEvent)

void UWBP_rec_effect_C::BaseCasts()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_rec_effect_C", "BaseCasts");

	UObject::ProcessEvent(Func, nullptr);
}

}

